Rewrite introduction to Composite Datasets.
lsst/LDM-463 pull request #25
Opened 2017-05-20 00:49 UTC by ktlim

This eliminates the Type 1, 2, 3 nomenclature and clarifies that Composite only refers to one object spanning many datasets.

2017-05-20 01:19 UTC, n8pease commented
looks good to me.

2017-05-24 19:30 UTC, gpdf requested changes
Please fix the capitalization and the grammar issue.  Discussion of IDs for collections can be handled separately later.

2017-05-24 19:30 UTC, gpdf commented on index.rst
> +Many (even potentially overlapping) datasets in one file is referred to as a "collection".
"are referred to"

2017-05-24 19:30 UTC, gpdf commented on index.rst
> +Many (even potentially overlapping) datasets in one file is referred to as a "collection".
or "A single file containing many (potentially overlapping) datasets is referred to as a 'collection'."

2017-05-24 19:30 UTC, gpdf commented on index.rst
> +Since there is nothing else special about them, they are not discussed further here.
This section seems to beg the question of what the DataIds for the individual datasets vs. the collection as a whole are / can be.  But that does not need to be addressed to complete this PR.

2017-05-24 19:30 UTC, gpdf commented on index.rst
> +A Composite dataset is made up of Component datasets, each of which may be any
"Composite" and "Component" are capitalized here but not above.

2017-05-24 22:49 UTC, gpdf approved these changes
Thanks!

2017-05-24 22:49 UTC, merged